### ISSUE TITLE
What C++ Runtime requirement?

### ISSUE THREAD

**Issue by Selur** [myrsloik/DotKill#4]
Trying to use the filter on a newly installed Windows (64bit Vapoursynth), I get:
```
Failed to evaluate the script:
Python exception: Failed to load C:/Program Files/Hybrid/64bit/vsfilters/DeCrawlFilter/DotKill/DotKill.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "C:\Users\Selur\AppData\Local\Temp\tempPreviewVapoursynthFile12_57_12_416.vpy", line 5, in <module>
    core.std.LoadPlugin(path="C:/Program Files/Hybrid/64bit/vsfilters/DeCrawlFilter/DotKill/DotKill.dll")
  File "src\cython\vapoursynth.pyx", line 2069, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load C:/Program Files/Hybrid/64bit/vsfilters/DeCrawlFilter/DotKill/DotKill.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```
script I use is:
```
# Imports
import vapoursynth as vs
core = vs.get_core()
# Loading Plugins
core.std.LoadPlugin(path="C:/Program Files/Hybrid/64bit/vsfilters/DeCrawlFilter/DotKill/DotKill.dll")
core.std.LoadPlugin(path="C:/Program Files/Hybrid/64bit/vsfilters/SourceFilter/FFMS2/ffms2.dll")
# source: 'C:\Users\Selur\Desktop\test.avi'
# current color space: YUV420P8, bit depth: 8, resolution: 640x352, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive
# Loading source using FFMS2
clip = core.ffms2.Source(source="C:/Users/Selur/Desktop/test.avi",cachefile="C:/Users/Selur/AppData/Local/Temp/avi_6e2ade859cf2b5d2a9d88bbd8bac59f3_853323747.ffindex",format=vs.YUV420P8,alpha=False)
# making sure input color matrix is set as 470bg
clip = core.resize.Point(clip, matrix_in_s="470bg",range_s="limited")
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip, fpsnum=25, fpsden=1)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# DeCrawling using DotKill
clip = core.dotkill.DotKillS(clip=clip)
# Output
clip.set_output()
```

since installing "Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14-27-29112" didn't help I wonder if you could share what C++ runtime is needed to use the filter. (otherwise I have to test any 64bit C++ runtime I can find,...)
(https://aka.ms/vs/16/release/vc_redist.x64.exe is the download link to the Redistributable package)
Cu Selur

**Comment by Selur** [comment]
I installed:
- Microsoft Visual C++ 2005 Redistributable (x64) - 8.0.61000
- Microsoft Visual C++ 2008 Redistributable (x64) - 9.0.30729.6161
- Microsoft Visual C++ 2010 Redistributable (x64) - 10.0.40219
- Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030.0
- Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664.0
- Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.27.29112.0
sadly it's still not working. Funny thing is that it's working on my main workstation using the same script.
-> so any hint what might be missing would be nice :)

**Comment by Selur** [comment]
okay, got it seems like an old version of dotkill snuck in
